apiVersion: cert-manager.io/v1  
kind: ClusterIssuer  
metadata:
  name: letsencrypt-cluster-issuer  
spec:
  acme:  
    server: https://acme-v02.api.letsencrypt.org/directory  # The ACME server URL for Let's Encrypt
    email: test@example.com  # The email address for Let's Encrypt account registration and recovery
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key  
    solvers:
    - http01:  
       ingress:
         class: nginx  
